---
language: csharp
solution: mono/GeoIP2.sln

env:
  global:
    - CONFIGURATION=Release
    - MAXMIND_BENCHMARK_DB=$TRAVIS_BUILD_DIR/GeoIP2.Benchmark/GeoLite2-City.mmdb
    - MAXMIND_TEST_BASE_DIR="$PWD/GeoIP2.UnitTests"

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    dotnet: 1.0.0-preview2-1-003177
    mono: none
    env: DOTNETCORE=1
    sudo: required
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    dotnet: 1.0.0-preview2-1-003177
    mono: none
    env: DOTNETCORE=1
  - os: linux
    dist: trusty # Ubuntu 14.04
    mono: latest
    sudo: false
  - os: osx
    osx_image: xcode7.3 # macOS 10.11
    mono: latest

script: ./dev-bin/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "IsbtLth0Yv5VcmUAR2wslanuzGkKVSsGIAKhT71rCimi3QAe/02MYqZsRvgcFdwSnRsrWqdIDQ2x1Rw7YT5k7TBUfr4TL2/KnP3dwgmCyfSQojsHXlwofnWGezkgYrat7rV2HvcboFF1WXf0lENA8RzmiCi0t2BWh4dl7kdPuSs=\n"
