language: csharp

before_install:
  - git submodule update --init --recursive
  - nuget restore GeoIP2.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xbuild
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./GeoIP2.UnitTests/bin/Debug/MaxMind.GeoIP2.UnitTests.dll

notifications:
  email:
    recipients:
      - dev@maxmind.com
    on_success: change
    on_failure: always
