---
language: csharp
solution: MaxMind.GeoIP2.sln

env:
  global:
    - MAXMIND_BENCHMARK_DB=$TRAVIS_BUILD_DIR/MaxMind.GeoIP2.UnitTests/TestData/MaxMind-DB/test-data/GeoIP2-City-Test.mmdb
    - MAXMIND_TEST_BASE_DIR="$PWD/MaxMind.GeoIP2.UnitTests"
    - CONFIGURATION=Release

matrix:
  include:
    - os: linux
      dotnet: 3.0
      mono: none
      sudo: required
      env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp3.0
    - os: osx
      dotnet: 3.0.101
      mono: none
      env: DOTNETCORE=1 CONSOLE_FRAMEWORK=netcoreapp3.0
    - os: linux
      mono: latest
      sudo: false

install: git submodule update --init --recursive

script: ./dev-bin/build.sh

notifications:
  email:
    on_failure: always
    on_success: change
    recipients:
      - dev-ci@maxmind.com
  slack:
    rooms:
      secure: "IsbtLth0Yv5VcmUAR2wslanuzGkKVSsGIAKhT71rCimi3QAe/02MYqZsRvgcFdwSnRsrWqdIDQ2x1Rw7YT5k7TBUfr4TL2/KnP3dwgmCyfSQojsHXlwofnWGezkgYrat7rV2HvcboFF1WXf0lENA8RzmiCi0t2BWh4dl7kdPuSs=\n"
