---
version: '1.0.{build}'

os: Visual Studio 2015

environment:
  global:
    MAXMIND_BENCHMARK_DB: GeoIP2.Benchmark/GeoLite2-City.mmdb
    MAXMIND_TEST_BASE_DIR: GeoIP2.UnitTests
  matrix:
    - CONFIGURATION: Debug
      FRAMEWORK: net45
      SECONDARYFRAMEWORK: net451
      FrameworkLibsMoniker: net45
    - CONFIGURATION: Release
      FRAMEWORK: net45
      SECONDARYFRAMEWORK: net451
      FrameworkLibsMoniker: net45
    - CONFIGURATION: Debug
      FRAMEWORK: netcoreapp1.0
      SECONDARYFRAMEWORK: netcoreapp1.0
      FrameworkLibsMoniker: netstandard1.4
    - CONFIGURATION: Release
      FRAMEWORK: netcoreapp1.0
      SECONDARYFRAMEWORK: netcoreapp1.0
      FrameworkLibsMoniker: netstandard1.4

before_build:
  - git submodule update --init --recursive

build_script:
  - ps: |
      if (gcm dotnet -errorAction SilentlyContinue) {
        echo "Using dotnet '$((gcm dotnet).Path)'"
        dotnet --info
      }
      else {
        echo "dotnet.exe not found"
        exit 1
      }

      # Restore Packages
      dotnet restore

      # Build Projects
      dotnet build -c $env:CONFIGURATION -f $env:FrameworkLibsMoniker .\GeoIP2
      dotnet build -c $env:CONFIGURATION -f $env:FRAMEWORK .\GeoIP2.Benchmark
      dotnet build -c $env:CONFIGURATION -f $env:SECONDARYFRAMEWORK .\GeoIP2.UnitTests

test_script:
  # Run Benchmark
  - dotnet run -f %FRAMEWORK% -c %CONFIGURATION% -p GeoIP2.Benchmark

  # Run Unit Tests
  - dotnet test -f %SECONDARYFRAMEWORK% -c %CONFIGURATION% GeoIP2.UnitTests

after_test:
  # Run Unit Tests
  - dotnet pack -c %CONFIGURATION% GeoIP2

artifacts:
  - path: 'GeoIP2\bin\**\*.nupkg'

notifications:
  - auth_token:
      secure: X+ymndzchVeC2LYsehzOt/GEMFfZJeTENeAU9lwNwTuCxBXFJNkuwZLd9joAtHgykHQoYqmEv/nH64+MA6nTlw==
    channel: ci
    on_build_failure: true
    on_build_status_changed: true
    on_build_success: true
    provider: Slack
  - on_build_failure: true
    on_build_status_changed: true
    on_build_success: false
    provider: Email
    subject: 'AppVeyor build {{status}}'
    to:
      - dev-ci@maxmind.com
