os: Visual Studio 2015 RC

install:
 - git submodule update --init --recursive
 - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

notifications:
- provider: Email
  to: dev@maxmind.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
